
export const productTypes = {
    FETCH_PRODUCTS_REQUEST : "FETCH_PRODUCTS_REQUEST",
    FETCH_PRODUCTS_SUCCESS : "FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAILURE : "FETCH_PRODUCTS_FAILURE", 
    GET_PRODUCTS: "GET_PRODUCTS",
    FETCH_DATA_REQUEST: "FETCH_DATA_REQUEST",
    FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
    FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE" 
}