
export const productTypes = {
    FETCH_PRODUCTS_REQUEST : "FETCH_PRODUCTS_REQUEST",
    FETCH_PRODUCTS_SUCCESS : "FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAILURE : "FETCH_PRODUCTS_FAILURE", 
    GET_PRODUCTS: "GET_PRODUCTS",  
}