

export const userTypes = {
   SING_IN_START: "SING_IN_START",
   SING_IN_SUCCESS: "SING_IN_SUCCESS",
   SING_IN_FAILURE: "SING_IN_FAILURE",
   SING_OUT_START: "SING_OUT_START",
   SING_OUT_SUCCESS: "SING_OUT_SUCCESS",
   SING_OUT_FAILURE: "SING_OUT_FAILURE",
   REGISTER_START: "REGISTER_START",
   REGISTER_SUCCESS: "REGISTER_SUCCESS",
   REGISTER_FAILURE: "REGISTER_FAILURE"
}